theme: jekyll-theme-cayman

title: Eclectic Casks
description: A macOS Homebrew tap!

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - Dangerfile
  - Casks/
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
